# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edgar K. Blog
email: edos@frtk.ru
description: | # this means to ignore newlines until "baseurl:"
        This blog is created under the
        Google Summer of Code 2017 programme.
        Copyright (c) 2017 Edgar A. Kaziakhmedov.
        All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edosedgar.github.io" # the base hostname & protocol for your site
github_username:  edosedgar
theme: jekyll-theme-midnight

# Build settings
markdown: kramdown
